### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by ismailarilik** [petrochenkov/classifui#1]
Hey there, thank you for this tool. I am trying to use it but somehow couldn't managed to. Could you please summarize the steps? And then I am also planning to add them to README.md.

**Comment by petrochenkov** [comment]
- Update path to rust repository on your machine in `fn main`.
- `cargo build --release`
- `./target/release/classifui --train`
- `./target/release/classifui --classify >classified.md`
- In `classified.md` tests with high-confidence are at the top, and low-confidence at the bottom. Each line shows top 3 candidate subdirectories with confidence scores (larger is better) and links to corresponding tests and issues.
